behaviors:
  Receive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 50600
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 1
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 256
