behaviors:
  Receive:
    trainer_type: ppo
    hyperparameters:
      batch_size: 320
      buffer_size: 10000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 3000
    summary_freq: 36000
